### ISSUE TITLE
32-bit support

### ISSUE THREAD

**Issue by Tiagoquix** [vulongm/copr-gamemode-git#1]
Hi there.

Could you provide `gamemode.i686` via COPR as well for 32-bit games?
(FYI, `gamemode.i686` from Fedora official repo requires `inih.i686`. The 64-bit version does not seem to require it AFAIK.)

Thanks in advance.

**Comment by vulongm** [comment]
I have modified the build to generate a 32-bit version and updated the instructions, let me know if that works.
