### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by Tiagoquix** [vulongm/copr-gamemode-git#2]
Hello. I am having a problem with this COPR package.

I know this isn't your fault, but I'm asking for help here because you may know more than I do.

Please see https://github.com/fedora-copr/copr/discussions/3360 for details.

**Comment by vulongm** [comment]
What version do you have installed currently?

**Comment by vulongm** [comment]
Oh I see what’s going on. I changed the version scheme to remove .90. Should be able to fix it by uninstalling and reinstalling the package. You can also wait until the tag switches over to 1.8.2, there hasn’t been many code changes in gamemode recently since the version your currently on.
