### ISSUE TITLE
Upstream package has been updated

### ISSUE THREAD

**Issue by Tiagoquix** [vulongm/copr-gamemode-git#3]
https://src.fedoraproject.org/rpms/gamemode/commits/rawhide
https://src.fedoraproject.org/rpms/gamemode/c/57968027f43363bd2159ab699eb898d2656fb064?branch=rawhide

Upstream package was changed.
Letting you know if anything in this COPR may need to be changed somehow (such as package config. files).

**Comment by vulongm** [comment]
Thanks, made some changes to mirror the upstream spec bd47959041a48c562491361a9244d25da11ee725
